- name: variables from play level
  hosts: localhost
  vars:
  - variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi I am learning {{course}}, Durations is {{duration}}"