- name: conditions
  hosts: localhost
  tasks:
  - name: check roboshop user exists or not
    ansible.builtin.debug: id roboshop
    register: user

- name: print variable value
  ansible.builtin.debug:
    msg: "User output is: {{user}}"