- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
     msg: "Hello {{item}}"
     state: present
    loop:
    - git
    - mysql
    - postfix